sudo: required
services:
 - docker 
before_install:
 - docker build -t guijarro/react-test -f ./client/Dockerfile.dev ./client
script:
 - docker run guijarro/react-test npm test -- --coverage

after_success
 - docker built -t guijarro/multi-client ./client
 - docker built -t guijarro/multi-nginx ./nginx
 - docker built -t guijarro/multi-server ./server 
 - docker built -t guijarro/multi-worker ./worker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push guijarro/multi-client
 - docker push guijarro/multi-nginx
 - docker push guijarro/multi-server
 - docker push guijarro/multi-worker
