language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t guijarro/react-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true guijarro/react-test npm test

after_success:
    - docker build -t mguijarro/multi-client ./client
    - docker build -t mguijarro/multi-nginx ./nginx
    - docker build -t mguijarro/multi-server ./server
    - docker build -t mguijarro/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push mguijarro/multi-client
    - docker push mguijarro/multi-nginx
    - docker push mguijarro/multi-server
    - docker push mguijarro/multi-worker

deploy:
   edge: true
   provider: elasticbeanstalk
   region: us-east-2
   app: multi-docker2
   env: MultiDocker2-env
   bucket_name: elasticbeanstalk-us-east-2-574350411057
   bucket_path: docker-multi
   on:
       branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: $AWS_SECRET_KEY
